version: '3'
  
services:
  apt-repo-server:
    build: .
    ports:
      - "8083:80"
    restart: always
    volumes:
      - ./debfiles:/mnt/data
      - ./default.conf.template /etc/nginx/conf.d/default.conf.template
